# Enable manage repository scripts
enable:
  - help
  - trust-escapace

# Default script
default: help
env:
  # https://github.com/dandavison/delta
  DELTA_VERSION: 0.17.0
  # https://github.com/sharkdp/fd
  FD_VERSION: 9.0.0
  # https://github.com/antonmedv/fx
  FX_VERSION: 32.0.0
  # https://github.com/grafana/k6
  K6_VERSION: 0.49.0
  # https://github.com/restic/restic
  RESTIC_VERSION: 0.16.4
  # https://github.com/caarlos0/svu
  SVU_VERSION: 1.12.0
  # https://github.com/antonmedv/walk/
  WALK_VERSION: 1.7.0
  # https://github.com/ajeetdsouza/zoxide
  ZOXIDE_VERSION: 0.9.4
