# Enable manage repository scripts
enable:
  - help
  - trust-escapace

# Default script
default: help
env:
  LLAMA_VERSION: 1.2.0
  RESTIC_VERSION: 0.14.0
  FD_VERSION: 8.3.2
  SVU_VERSION: 1.9.0
  ZOXIDE_VERSION: 0.8.1
  DELTA_VERSION: 0.13.0
  K6_VERSION: 0.42.0
