# Enable manage repository scripts
enable:
  - help
  - trust-escapace

# Default script
default: help
env:
  LLAMA_VERSION: 1.4.0
  RESTIC_VERSION: 0.15.2
  FD_VERSION: 8.7.0
  SVU_VERSION: 1.10.2
  ZOXIDE_VERSION: 0.9.1
  DELTA_VERSION: 0.16.5
  K6_VERSION: 0.44.1
