# Enable manage repository scripts
enable:
  - help
  - trust-escapace

# Default script
default: help
env:
  WALK_VERSION: 1.6.2
  RESTIC_VERSION: 0.15.2
  FD_VERSION: 8.7.0
  SVU_VERSION: 1.11.0
  ZOXIDE_VERSION: 0.9.2
  DELTA_VERSION: 0.16.5
  K6_VERSION: 0.44.1
